### ISSUE TITLE
Service named squid3 rather than squid

### ISSUE THREAD

**Issue by johtso** [saltstack-formulas/squid-formula#2]
```yaml
          ID: squid
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: squid.
     Changes:
              ----------
              libcap2:
                  ----------
                  new:
                      1:2.22-1ubuntu3
                  old:

              libltdl7:
                  ----------
                  new:
                      2.4.2-1ubuntu1
                  old:

              squid:
                  ----------
                  new:
                      3.1.19-1ubuntu3.12.04.2
                  old:

              squid-langpack:
                  ----------
                  new:
                      20111114-1
                  old:

              squid3:
                  ----------
                  new:
                      3.1.19-1ubuntu3.12.04.2
                  old:

              squid3-common:
                  ----------
                  new:
                      3.1.19-1ubuntu3.12.04.2
                  old:

              ssl-cert:
                  ----------
                  new:
                      1.0.28ubuntu0.1
                  old:

----------
          ID: squid
    Function: file.managed
        Name: /etc/squid/squid.conf
      Result: True
     Comment: File /etc/squid/squid.conf updated
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: squid
    Function: service.running
      Result: False
     Comment: Failed to start the service
     Changes:
              ----------
              squid:
                  False

Summary
------------
Succeeded: 2
Failed:    1
------------
Total:     3
```

**Comment by daschatten** [comment]
On current debian and ubuntu versions squid3 is the most recent squid version. So if an old version is needed the defaults in map.jinja could be overwritten in pillar with:
```
squid:
  lookup:
    pkgs:
      - squid
    service: squid
    conf_dir: /etc/squid
```
